export const TeamData = [
  {
    id: '1',
    img: '/images/team/ayaz.jpg',
    details: `Ayaz Ahmad is Digital Marketing Executive at DigiPremier, also recognized as SEO Genius — DigiPremier one of the award-winning, high-end, digital business solution agencies. A keynote speaker, creative trainer, and Google Ads Certified, he is an SEO, SEM, Display Ads, Lead generator, and content marketing specialist.`,
    Name: 'Smith Dcusa',
    desig: 'Co-Founder',
    facebook: 'https://www.facebook.com/AyazAhmad01',
    linkedin: 'https://www.linkedin.com/in/ayazahmad01/',
    twitter: 'https://twitter.com/meharayazahmad',
    instagram: 'https://www.instagram.com/ayazahmadmehar/',
  },
  {
    id: '2',
    img: '/images/team/danish.jpg',
    details:
      'I am responsible for designing and implementing UI components for JavaScript-based web applications and mobile applications with the use of modern technologies like MERN Stack development.',
    Name: 'Lora Smith Deo',
    desig: 'Executive',
    facebook: '',
    linkedin: '',
    twitter: '',
    instagram: '',
  },
  {
    id: '3',
    img: '/images/team/awais.jpg',
    details:
      'I worked as mobile application developer. In this advance erra I work on new tech & explore how I give more appropriate application to our customers in a very efficient way.',
    Name: 'Ana Richmono',
    desig: 'Creative Leader',
    facebook: '',
    linkedin: '',
    twitter: '',
    instagram: '',
  },
  {
    id: '4',
    img: '/images/team/naveed.jpg',
    details: `Naveed Aziz is one of Lahore, Pakistan's leading internet marketers. He is a distinguished keynote lecturer, businessman, SEO specialist. Over 7 years in the fields of SEO, internet and UX, he has been engaged in digital marketing.`,
    Name: 'Ana Richmono',
    desig: 'Creative Leader',
    facebook: '',
    linkedin: '',
    twitter: '',
    instagram: '',
  },
]
